### ISSUE TITLE
Not working Python37

### ISSUE THREAD

**Issue by JonhSilver** [0x454447415244/HandwritingRecognitionSystem#10]
c:\Python37>python.exe HR\train.py
W0709 14:09:30.364569  6332 deprecation_wrapper.py:119] From HR\train.py:41: The
 name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0709 14:09:30.366611  6332 deprecation_wrapper.py:119] From c:\Python37\HR\cnn.
py:71: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variabl
e_scope instead.

W0709 14:09:30.367612  6332 deprecation_wrapper.py:119] From c:\Python37\HR\util
.py:40: The name tf.truncated_normal is deprecated. Please use tf.random.truncat
ed_normal instead.

W0709 14:09:30.459672  6332 deprecation_wrapper.py:119] From c:\Python37\HR\util
.py:47: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d inste
ad.

W0709 14:09:31.796136  6332 lazy_loader.py:50]
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-su
nset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0709 14:09:31.797139  6332 deprecation.py:323] From c:\Python37\HR\rnn.py:73: L
STMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and wi
ll be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by th
at in Tensorflow 2.0.
W0709 14:09:31.798139  6332 deprecation.py:323] From c:\Python37\HR\rnn.py:74: M
ultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated an
d will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replace
d by that in Tensorflow 2.0.
W0709 14:09:31.800641  6332 deprecation.py:323] From c:\Python37\HR\rnn.py:81: b
idirectional_dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will
 be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equiva
lent to this API
W0709 14:09:31.801141  6332 deprecation.py:323] From c:\Python37\lib\site-packag
es\tensorflow\python\ops\rnn.py:464: dynamic_rnn (from tensorflow.python.ops.rnn
) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
W0709 14:09:32.159433  6332 deprecation.py:506] From c:\Python37\lib\site-packag
es\tensorflow\python\ops\rnn_cell_impl.py:961: calling Zeros.__init__ (from tens
orflow.python.ops.init_ops) with dtype is deprecated and will be removed in a fu
ture version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the c
onstructor
W0709 14:09:32.971470  6332 deprecation.py:323] From c:\Python37\lib\site-packag
es\tensorflow\python\ops\rnn.py:244: add_dispatch_support.<locals>.wrapper (from
 tensorflow.python.ops.array_ops) is deprecated and will be removed in a future
version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0709 14:09:33.300187  6332 deprecation_wrapper.py:119] From HR\train.py:61: The
 name tf.nn.ctc_loss is deprecated. Please use tf.compat.v1.nn.ctc_loss instead.

W0709 14:09:33.302189  6332 deprecation_wrapper.py:119] From HR\train.py:65: The
 name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar in
stead.

W0709 14:09:33.304190  6332 deprecation.py:323] From HR\train.py:70: to_int32 (f
rom tensorflow.python.ops.math_ops) is deprecated and will be removed in a futur
e version.
Instructions for updating:
Use `tf.cast` instead.
W0709 14:09:33.309194  6332 deprecation.py:323] From HR\train.py:72: to_float (f
rom tensorflow.python.ops.math_ops) is deprecated and will be removed in a futur
e version.
Instructions for updating:
Use `tf.cast` instead.
W0709 14:09:33.311257  6332 deprecation_wrapper.py:119] From HR\train.py:76: The
 name tf.trainable_variables is deprecated. Please use tf.compat.v1.trainable_va
riables instead.

W0709 14:09:35.607799  6332 deprecation_wrapper.py:119] From HR\train.py:80: The
 name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOp
timizer instead.

Reading ./samples/Images//000033/READ17.000033_01_01_pg_line_1486644351571_780.p
ng
Reading ./samples/Images//000033/READ17.000033_01_02_pg_line_1486644356245_781.p
ng
Traceback (most recent call last):
  File "HR\train.py", line 95, in <module>
    inputList, seqLens, targetList = ReadData(cfg.TRAIN_LOCATION, cfg.TRAIN_LIST
, cfg.TRAIN_NB, WND_HEIGHT, WND_WIDTH, WND_SHIFT, VEC_PER_WND, cfg.TRAIN_TRANS)
  File "c:\Python37\HR\util.py", line 130, in ReadData
    h, w = np.shape(image)
ValueError: not enough values to unpack (expected 2, got 0)

c:\Python37>

**Comment by 0x454447415244** [comment]
Hello, make sure that images exist and are valid. For instance, check if the image at path "./samples/Images//000033/READ17.000033_01_02_pg_line_1486644356245_781.png" exists and valid.

Let me know if that helps.

**Comment by JonhSilver** [comment]
Image exist and valid

**Comment by 0x454447415244** [comment]
I see that the error happens on the second image, namely:
./samples/Images//000033/READ17.000033_01_02_pg_line_1486644356245_781.png
