### ISSUE TITLE
GENERATE CHECK POINT 

### ISSUE THREAD

**Issue by PrakharPrashantSingh** [0x454447415244/HandwritingRecognitionSystem#11]
Hi, i passed the training step (using train.py file) and model directory is created but the thing is there is no model at all. However i can see the log file but no checkpoint at all.

In shot, i want to ask how to generate a checkpoint  (model) to test this script.

Thanks

**Comment by 0x454447415244** [comment]
Hello, a checkpoint is generated each n epochs where n is a parameter to be configure in config.py. You need to change the value of SaveEachNEpochs and set it to 1 if you want to generate a model every epoch. Please note that an epoch is equivalent to feeding the model all the training data.

**Comment by PrakharPrashantSingh** [comment]
okay i will have a look and let you know.

Thanks for your help!
