### ISSUE TITLE
ValueError: Variable RNN_1

### ISSUE THREAD

**Issue by thomas4721** [0x454447415244/HandwritingRecognitionSystem#19]
![image](https://user-images.githubusercontent.com/33492029/112974566-d1659600-917c-11eb-9824-6e5c189d0984.png)
i got this problem when i try to run train.py
any solution my friend? because i'm trying to understand the flow of program for my Thesis

**Comment by thomas4721** [comment]
okay, i find the solution but then this is happening
![image](https://user-images.githubusercontent.com/33492029/112975462-e262d700-917d-11eb-9db9-9d9286ab6d46.png)
is thit suppose to be like that or is there some error??

**Comment by 0x454447415244** [comment]
Hi, this is not an error. It is some Tensorflow-generated runtime information.
You can check the created logs file to see the training progress.
