### ISSUE TITLE
Training Data and `No checkpoint found`

### ISSUE THREAD

**Issue by ArunLukeDsouza** [0x454447415244/HandwritingRecognitionSystem#21]
The README says

_To help run the system, sample images from ICDAR2017 Competition on Handwritten Text Recognition on the READ Dataset are added._

I tried reproducing the results of your work by running `python3 compute_probs.py` and `python3 test.py`  both of which yielded `No checkpoint found` after the script reads images successfully.
`
Reading ./samples/Images//000033/READ17.000033_01_18_pg_line_1486644440417_797.png
Reading ./samples/Images//000033/READ17.000033_01_19_pg_line_1486644445527_798.png
Reading ./samples/Images//000033/READ17.000033_01_20_pg_line_1486644453911_799.png
Initializing...
2021-04-06 08:41:30.589865: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorF
low binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following
 CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
`

Would you mind sharing the checkpoint file? 

Can the _ICDAR2017 Competition on Handwritten Text Recognition on the READ Dataset_ be used to train the model? If yes, please provide details on it's implementation. The link to the dataset in the README is also broken, is [this](https://zenodo.org/record/835489#.YGv1hy0RpQI) the same dataset?

Please Advise.

Thank you for your time.

**Comment by 0x454447415244** [comment]
You need to train the system before you can run test.py or compute_probs.py.
The dataset is available online, you just need to download it and train the system as described.
