### ISSUE TITLE
How to train the model on the full image recognition after the training on the samples

### ISSUE THREAD

**Issue by engreememad** [0x454447415244/HandwritingRecognitionSystem#22]
Hello,
I found your code is amazing and give best results for the handwriting document recognition ,but when I work on it  I found difficulties to train the model on the full page after the manually labeled text-line images in the samples?

**Please can you give me a samples for "how to train the model on full images and the .tru file of it"?**

because I am trying to run it on a different data set for my research and your paper is the state-of-the-art solution.
and I study the config.py but I don't find the way to add full image after the train on lines image

**Comment by 0x454447415244** [comment]
This system is designed to recognize text-line images. Recognizing text in paragraphs or full pages is not end-to-end. It requires that you pre-segment the pages into text-line images.
