### ISSUE TITLE
What kind of training time can I expect without a GPU

### ISSUE THREAD

**Issue by stevethearkiv** [0x454447415244/HandwritingRecognitionSystem#4]
Hi. I know this isn't really an "issue" per se, but it might be useful to have it visible on the site for others who have the same question. 

I am running the training now, and its been running for a few hours ( I have no Tensor compatible GPU ).

Is it worth my while purchasing a GPU, or will training finish within a few hours on a regular PC?

**Comment by 0x454447415244** [comment]
Yes. It is worth getting a GPU if you are working on images. You should expect around 10x speedup. The training time depends on your amount of data.
