### ISSUE TITLE
Error when try to run test.py

### ISSUE THREAD

**Issue by Syafiq-lab** [0x454447415244/HandwritingRecognitionSystem#5]
![capture](https://user-images.githubusercontent.com/33047895/49505601-1207ba00-f8b7-11e8-8cab-4e00551bbf67.PNG)
this is error i got.  Also the util.py does not recoize import tensorflow as tf.

**Comment by 0x454447415244** [comment]
Hello, I could not reproduce this issue.
Make sure you have the latest version of the code.

**Comment by GireeshS22** [comment]
Hi,

In my version of tensorflow (1.3.0) there is no leaky relu module.

**Comment by mayang1** [comment]
can you share your preprocessed dataset?
