### ISSUE TITLE
module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'

### ISSUE THREAD

**Issue by GireeshS22** [0x454447415244/HandwritingRecognitionSystem#7]
Hi,

In my version of TF (1.3.0) there is no leaky_relu module.

Can you please indicate the version of TF used?

Thanks,
Gireesh

**Comment by 0x454447415244** [comment]
As far as I know, a native support for leaky_relu has been added since Tensorflow 1.4. You can:
- Use relu instead.
- Update your Tensorflow.
- Use your own implementation of leaky_relu:
```
def leaky_relu(x, alpha):
  return tf.nn.relu(x) - alpha * tf.nn.relu(-x)
```
