### ISSUE TITLE
Support for TensorBoard for visualizing the network

### ISSUE THREAD

**Issue by kriato** [0x454447415244/HandwritingRecognitionSystem#8]
I noticed that there is a SummaryWriter that writes files in the summary folder. I am trying tensorboard on that folder and I keep getting "Found more than one metagraph event per run. Overwriting the metagraph with the newest event." Any suggestion to make it work fine?

**Comment by 0x454447415244** [comment]
You need to clean (rm -f ./summary/*) or backup/save (if you need it later) the summary directory between runs. If you don't, then data from different experiments will be written to the same graph.
